/*
 * Resonance Memory
 * Copyright (C) 2026 Samuel Jackson Grim
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * build-exe.js - regenerate the single-file executable from the source files.
 *
 * Sources stay the editable truth (server.js, field.js, ledger.js, panel.js, entry.js).
 * This just re-bundles them into one exe. Run it again after any edit:
 *     node build-exe.js
 *
 * Pipeline: esbuild (bundle to one file) -> Node SEA blob -> copy node runtime ->
 * postject (inject blob). Produces resonance-memory.exe (Windows) / memory (mac/linux) that
 * needs NO Node installed on the user's machine.
 */
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const dir = __dirname;
const build = path.join(dir, "build");
fs.mkdirSync(build, { recursive: true });

const exeName = process.platform === "win32" ? "resonance-memory.exe" : "memory";
const outExe = path.join(dir, exeName);
const run = (cmd) => execSync(cmd, { stdio: "inherit", cwd: dir });

// Bake the runtime data files INTO the bundle so the shipped product is a single
// exe - no loose demo-seed.jsonl / system-prompt.md next to it. panel.js reads these
// from disk first (dev) and falls back to the embedded copy (shipped exe).
console.log("[0/5] embedding runtime assets (demo seed, system prompt) ...");
const readOr = (f) => { const p = path.join(dir, f); return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : ""; };
fs.writeFileSync(
  path.join(dir, "embedded-assets.js"),
  "// GENERATED by build-exe.js - do not edit; regenerated every build.\n" +
  "module.exports = {\n" +
  "  demoSeed: " + JSON.stringify(readOr("demo-seed.jsonl")) + ",\n" +
  "  systemPrompt: " + JSON.stringify(readOr("system-prompt.md")) + "\n};\n"
);

console.log("[1/4] bundling sources with esbuild ...");
// --legal-comments=none drops the per-file AGPL header that sits atop every source,
// so the bundle isn't peppered with a dozen identical notices. We add ONE notice
// back as a top-of-file banner below.
const bundleFile = path.join(build, "bundle.js");
run(`npx --yes esbuild "${path.join(dir, "entry.js")}" --bundle --platform=node --target=node22 --legal-comments=none --outfile="${bundleFile}"`);

// One clean license banner at the very top of the bundle, in place of the many
// per-file headers. Defensively strip any header block esbuild happened to keep.
const licenseBanner =
  "/*\n" +
  " * Resonance Memory\n" +
  " * Copyright (C) 2026 Samuel Jackson Grim\n" +
  " *\n" +
  " * This program is free software: you can redistribute it and/or modify\n" +
  " * it under the terms of the GNU Affero General Public License as published by\n" +
  " * the Free Software Foundation, either version 3 of the License, or\n" +
  " * (at your option) any later version.\n" +
  " *\n" +
  " * This program is distributed in the hope that it will be useful,\n" +
  " * but WITHOUT ANY WARRANTY; without even the implied warranty of\n" +
  " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" +
  " * GNU Affero General Public License for more details.\n" +
  " *\n" +
  " * You should have received a copy of the GNU Affero General Public License\n" +
  " * along with this program.  If not, see <https://www.gnu.org/licenses/>.\n" +
  " */\n";
let bundled = fs.readFileSync(bundleFile, "utf8");
// Remove any surviving copies of the exact per-file header block, then prepend one.
bundled = bundled.replace(/\/\*\r?\n \* Resonance Memory\r?\n[\s\S]*?www\.gnu\.org\/licenses\/>\.\r?\n \*\/\r?\n?/g, "");
fs.writeFileSync(bundleFile, licenseBanner + bundled);

console.log("[2/4] generating SEA blob ...");
run(`"${process.execPath}" --experimental-sea-config "${path.join(dir, "sea-config.json")}"`);

console.log("[3/4] copying the node runtime -> " + exeName + " ...");
if (fs.existsSync(outExe)) fs.rmSync(outExe);
fs.copyFileSync(process.execPath, outExe);

console.log("[4/4] injecting blob (postject) ...");
const fuse = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2";
let inject = `npx --yes postject "${outExe}" NODE_SEA_BLOB "${path.join(build, "sea-prep.blob")}" --sentinel-fuse ${fuse}`;
if (process.platform === "darwin") inject += " --macho-segment-name NODE_SEA";
run(inject);

// Flip the Windows PE subsystem console(3) -> GUI(2) so double-clicking the exe opens
// NO console window. MCP mode is unaffected: LM Studio pipes stdin/stdout, and a GUI-
// subsystem process uses those redirected handles fine - it just doesn't auto-allocate
// a console when launched interactively. This makes the exe the single, clean thing to
// double-click (no separate launcher, no stray terminal).
if (process.platform === "win32") {
  const buf = fs.readFileSync(outExe);
  const peOff = buf.readUInt32LE(0x3c);
  const subOff = peOff + 92; // PE sig(4) + COFF header(20) + optional-header Subsystem field(0x44)
  if (buf.readUInt16LE(subOff) === 3) {
    buf.writeUInt16LE(2, subOff);
    fs.writeFileSync(outExe, buf);
    console.log("      subsystem flipped console -> GUI (no console window on double-click)");
  }
}

const mb = (fs.statSync(outExe).size / 1048576).toFixed(0);
console.log("\nDone -> " + outExe + "  (" + mb + " MB)");

// Stage the clean, ship-ready bundle: ONLY what a user needs, nothing else. This is
// the folder you zip and hand out - no source, no build scripts, no sprawl.
console.log("[5/5] staging dist/ (the shippable bundle) ...");
const dist = path.join(dir, "dist");
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });
// The distributable is the single exe - everything a user needs is baked in.
fs.copyFileSync(outExe, path.join(dist, exeName));
console.log("Staged the single-file distributable -> " + path.join(dist, exeName));
console.log('\nTest:  "' + outExe + '" --mcp   (MCP server)   |   "' + outExe + '"   (control panel)');
